name: akademi_ek_ders_3
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #FIREBASE
  firebase_auth: ^3.3.9
  firebase_core: ^1.13.1
  cloud_firestore: ^3.1.10
  #STATE_MANAGEMENT
  stacked: ^2.2.8
  #NETWORK
  dio: ^4.0.4
  json_annotation: ^4.0.0
  json_serializable: ^4.0.3
  retrofit: '>=3.0.0 <4.0.0'
  #UTILS
  cupertino_icons: ^1.0.2
  animations: ^2.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner:

flutter:

  uses-material-design: true

  assets:
    - assets/